# -*- coding: utf-8 -*-
"""Copy of app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e4gdxpQHuovNBo6Hb3DN8tC7_xK1zvhI
"""

import streamlit as st
import torch
from torchvision import models, transforms
from PIL import Image
import urllib.request
import os

# 1. SETUP THE PAGE
st.title("Age on Hoof")
st.write("Upload a photo of a buck to estimate its age.")

# 2. LOAD YOUR BRAIN (The .pth file)
@st.cache_resource
def load_model():
    model_path = 'deer_model_v1.pth'

    # DOWNLOAD FROM GITHUB ASSETS IF NOT PRESENT
    if not os.path.exists(model_path):
        # REPLACE THE LINK BELOW with the one you copied from your GitHub Assets
        url = "https://github.com/benjaminwiley1011-stack/Bucks/releases/download/v1.0/deer_model_v1.1.pth"
        with st.spinner('Downloading AI brain... please wait.'):
            urllib.request.urlretrieve(url, model_path)

    model = models.resnet18()
    num_ftrs = model.fc.in_features
    model.fc = torch.nn.Linear(num_ftrs, 4)

    # Load onto CPU (since websites usually don't have GPUs)
    model.load_state_dict(torch.load(model_path, map_location=torch.device('cpu')))
    model.eval()
    return model

model = load_model()

# 3. FILE UPLOADER
uploaded_file = st.file_uploader("Choose a deer photo...", type="jpg")

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert('RGB') # Ensures it works with PNGs too
    st.image(image, caption='Uploaded Image', use_column_width=True)

    preprocess = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])

    img_t = preprocess(image).unsqueeze(0)

    # 4. PREDICT
    with torch.no_grad():
        output = model(img_t)
        _, predicted = torch.max(output, 1)
        classes = ['1.5', '2.5', '3.5', '4.5']

    st.success(f"Estimated Age: {classes[predicted.item()]} years old")

# Run this code cell to create the file in your Colab sidebar
with open('requirements.txt', 'w') as f:
    f.write('torch\ntorchvision\npillow\nstreamlit')

print("requirements.txt has been created in the files sidebar!")

